//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПП
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SettingsManagerEntities : DbContext
    {
        public SettingsManagerEntities()
            : base("name=SettingsManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoAction> AutoActions { get; set; }
        public virtual DbSet<MonitoringData> MonitoringData { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<StartupItem> StartupItems { get; set; }
        public virtual DbSet<SystemSettings> SystemSettings { get; set; }
    }
}
