//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПП
{
    using System;
    using System.Collections.Generic;

    public class MonitoringData
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public double CpuUsage { get; set; } // в процентах
        public double MemoryUsage { get; set; } // в процентах
        public double NetworkIn { get; set; } // в МБ
        public double NetworkOut { get; set; } // в МБ
    }
}
