//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПП
{
    using System;
    using System.Collections.Generic;

    //public class Profile
    //{
    //    public int Id { get; set; }
    //    public string Name { get; set; }
    //    public string Description { get; set; }
    //    public DateTime CreatedDate { get; set; } = DateTime.Now;
    //    public bool IsDefault { get; set; }
    //    public string IconPath { get; set; }
    //    public string ThemeSettings { get; set; }
    //    public string AssociatedApps { get; set; } // JSON список приложений
    //}
    public class Profile
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsDefault { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}
