//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПП
{
    using System;
    using System.Collections.Generic;

    public class SystemSettings
    {
        public int Id { get; set; }
        public string Theme { get; set; } = "Dark";
        public string Language { get; set; } = "Russian";
        public bool AutoUpdates { get; set; } = true;
        public bool SendStatistics { get; set; } = false;
        public string LogsPath { get; set; } = @"C:\ProgramData\SettingsManager\Logs";
    }
}
